### ISSUE TITLE
트위치에서 광고가 나옴

### ISSUE THREAD

**Issue by agpumboy** [seia-soto/filter-kr#2]
![image](https://user-images.githubusercontent.com/94548284/142229391-49a3cca8-d86a-4c9c-96f0-1ab3b1bf7b99.png)
트위치에서 광고 관련 URL을 업데이트했는지는 몰라도 트위치에서만 광고가 나옵니다. 처리 가능하나요?

**Comment by seia-soto** [comment]
Closing due to outdated issue.
