### ISSUE TITLE
애드쉴드의 모든 광고 형태

### ISSUE THREAD

**Issue by seia-soto** [seia-soto/filter-kr#4]
**현재 항목은 지속적으로 업데이트 예정인 항목입니다.**

## 개요

[애드쉴드](https://www.ad-shield.io/)에서는 광고가 차단당하지 않도록 Shadow DOM 등의 기술 등을 사용하고 있습니다.

결국 웹 기술에 귀결되므로 기존의 필터 규칙들로는 차단이 불가능해보이지만 가능합니다.

하지만 차단에 있어서 false-positive를 피하기 위해 규칙은 바로 게시되지 않습니다.

![image](https://user-images.githubusercontent.com/30369714/158069564-6f770e86-99f8-48b2-8d7a-a67326bf9568.png)

**Comment by seia-soto** [comment]
## 20220314

당일 광고 개체를 ㅍㅍㅅㅅ에서 발견하였으며 정상적으로 차단에 성공하였으나 타 웹 사이트에서 false-positive인 경우가 존재할 수 있어 공개 보류 중입니다.

**Comment by piquark6046** [comment]
Useful Resource:
- https://github.com/uBlockOrigin/uBlock-issues/issues/1741

**Comment by seia-soto** [comment]
> Useful Resource:
> 
>     * [Protect RegExp.prototype.test method in scriptlets.js uBlockOrigin/uBlock-issues#1741](https://github.com/uBlockOrigin/uBlock-issues/issues/1741)

Instead of using static filtering, updated the rule based on static inline script filtering method.

#61c5fbb

**Comment by seia-soto** [comment]
## 20220315 - var 2

애드쉴드에서 업데이트를 감행하며 차단하기가 더 단순해졌습니다. 더 이상 Inline Script Blocking을 고려하지 않아도 되어 남은 길이 단순해졌습니다. 광고 숨기기는 이제 더 쉽습니다.

단순히 그냥 숨기세요.

```css
ppss.kr###genesis-content > *:not(:has(header)):style(display: none)
```

### 통합 상태

- https://github.com/yous/YousList/pull/214

**Comment by seia-soto** [comment]
## 20220315

애드쉴드의 경우에는 웹 사이트와 깊게 통합되어 있어 단순 개체 숨기기로는 차단하기 어려운 경우가 많습니다.

즉, 웹 사이트의 광고 영역을 차단하는 것이 훨씬 빠릅니다.

애드쉴드는 더 이상 광고의 주체로 판단하지 않고 개별 웹 사이트를 차단하는 것을 목표로 합니다.

**Comment by seia-soto** [comment]
애드쉴드는 애드쉴드 측의 업데이트에 불구하고 Firefox에서 더 보이지 않습니다. 당분간 업데이트 예정은 없습니다.

**Comment by seia-soto** [comment]
애드쉴드를 적용하는 웹 사이트가 다시 늘어남에 따라 다시 애드쉴드 차단을 포커싱합니다.

**Comment by seia-soto** [comment]
## v20220406 - var 2

```css
loawa.com,ppss.kr,inven.co.kr,tgd.kr,ygosu.com##+js(set, scrollY, undefined)
```

**Comment by seia-soto** [comment]
## v20220423

```css
loawa.com,ygosu.com,inven.co.kr,ppss.kr,tgd.kr##+js(set, outerHeight, 0)
```

**Comment by seia-soto** [comment]
## v20220513

```css
ppss.kr,ygosu.com,tgd.kr,inven.co.kr,loawa.com,feedclick.net##+js(nostif, eval, 1000)
```

**Comment by seia-soto** [comment]
## v20220520

```css
ppss.kr,ygosu.com,tgd.kr,inven.co.kr,loawa.com,feedclick.net##+js(nostif, , 10)
```

**Comment by seia-soto** [comment]
## v20220528

```css
ppss.kr,feedclick.net##+js(aopw, document.writeln)
ygosu.com,tgd.kr,loawa.com,inven.co.kr##+js(nostif, const, 11)
```

**Comment by seia-soto** [comment]
## v20220604

```css
feedclick.net,loawa.com##div:not([id])>div[style="margin-left: auto;"]::before:style(content: ''; display: block; position: absolute; top: 0; left: 0; z-index: 2; height: 100%; width: 100%; background: #1F1F1F;)
inven.co.kr##div[style=""]>div[style="margin-left: auto;"]::before:style(content: ''; display: block; position: absolute; top: 0; left: 0; z-index: 2; height: 249px; width: 250px; background: white;)
inven.co.kr##div[style="width: 728px; height: 90px;"]>div[style="margin-left: auto;"]::before:style(content: ''; display: block; position: absolute; top: 0; left: 0; z-index: 2; height: 100px; width: 800px; background: white;)
ppss.kr##div[style=""]>div[style="margin-left: auto;"]::before:style(content: ''; display: block; position: absolute; top: 0; left: 0; z-index: 2; height: 100%; width: 100%; background: white;)
```

**Comment by seia-soto** [comment]
## v20220607

```css
inven.co.kr,loawa.com,ppss.kr##+js(json-prune, tracker_urls.[].url)
```

**Comment by seia-soto** [comment]
## v20220608

```css
inven.co.kr,loawa.com,ppss.kr,feedclick.net,ygosu.com##style+div:nth-last-child(1)
inven.co.kr,loawa.com,ppss.kr,feedclick.net,ygosu.com##+js(set, HTMLImageElement.prototype.removeAttribute, noopFunc)
inven.co.kr,loawa.com,ppss.kr,feedclick.net,ygosu.com##+js(set, outerHeight, 0)
```

**Comment by seia-soto** [comment]
Completely Fixed with UserScript.
